version: '3.4'

services:
   Ordersmicroservice.api:
    build:
      context: H:\OrderMicroservice
      dockerfile: OrdersMicroservice.API/Dockerfile
    image: vishwasjce/orders-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "9000:8080"   # Swagger available at http://localhost:6000/swagger
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
