services:
  Ordersmicroservice.api:
    build:
      context: H:\OrderMicroservice
      dockerfile: OrdersMicroservice.API/Dockerfile
    image: vishwasjce/orders-service:latest
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:8080"
    networks:
      - my-internal-net
   

networks:
  my-internal-net:
    external: true
